# Generated by Django 6.0.2 on 2026-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('setCode', models.TextField(db_column='setCode')),
                ('rarity', models.TextField()),
                ('layout', models.TextField()),
                ('isFunny', models.BooleanField(db_column='isFunny', null=True)),
                ('isOnlineOnly', models.BooleanField(db_column='isOnlineOnly', null=True)),
                ('isOversized', models.BooleanField(db_column='isOversized', null=True)),
                ('availability', models.TextField(null=True)),
                ('side', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardIdentifiers',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('scryfallId', models.TextField(db_column='scryfallId', null=True)),
            ],
            options={
                'db_table': 'cardIdentifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1_uuid', models.TextField()),
                ('card_2_uuid', models.TextField()),
                ('chosen_uuid', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matchup_vote',
            },
        ),
    ]
