# Generated by Django 6.0.2 on 2026-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_matchup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('rating', models.FloatField(default=1500.0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'matchup_cardrating',
            },
        ),
    ]
